spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto = update
spring.flyway.schemas.table=flyway_schema_history
spring.flyway.baseline-on-migrate=true
spring.flyway.sql-migration-prefix=V
spring.flyway.repeatable-sql-migration-prefix=R
spring.flyway.sql-migration-separator=__
spring.flyway.sql-migration-suffixes=.sql
spring.flyway.validateOnMigrate=false

# collection api values
collection.images.s3.bucket="collection-images"
minio.s3.url="http://127.0.0.1:9000"
minio.s3.access.key="Z09TXYzfmu2q01ScKRfy"
#minio.s3.access.key="wQ17a7yxKjV0U27IIike"
minio.s3.secret.key="NnPLNtYCnZsWyPZfrxOlnaedkEi7c9hykFs14wj5"
#minio.s3.secret.key="FPLMGbg0jhrOT1bzaFlgA6PHU2Btupiy0ncYQpZS"

