server:
  port: 8088
cors:
  allowed-origins:
    - "http://localhost:5173"
    - "http://localhost:5174"
    - "http://localhost:3000"
    - "http://localhost:4173/"
collection:
  images:
    s3:
      bucket: collection-images
minio:
  s3:
    access:
      key: ${MINIO_ACCESS_KEY}
    secret:
      key: ${MINIO_SECRET_KEY}
    url: ${MINIO_URL}
spring:
  profiles:
    active: ${ENV_APP}
  datasource:
    url: jdbc:postgresql://${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    repeatable-sql-migration-prefix: R
    schemas:
      table: flyway_schema_history
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validateOnMigrate: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
