spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/collectibles
spring.datasource.username=m32116
spring.datasource.password=dbconnect23
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
